version: '3.7'
services:
  api:
    build: .
    ports:
      - "5002:80"
    environment:
      DB_HOST: db
      DB_USER: master_user
      DB_PASS: password123
      DB_NAME: todos
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: master_user
      POSTGRES_DB: todos